"""
SPICE Exporter – converts abstract device dictionaries into NGSpice netlists.
"""

from datetime import datetime
from typing import List


class SpiceExporter:
    HEADER = [
        "*-------------------------------------------",
        "*  Auto-generated by Analog-GPT",
        "*-------------------------------------------",
        ".include 65nm.lib",
        ".param temp=27",
    ]

    FOOTER = [
        ".control",
        "  op",
        "  ac dec 100 1 1e9",
        "  write output.raw",
        ".endc",
        ".end",
    ]

    def assemble(self, body_lines: List[str]) -> str:
        now = datetime.utcnow()
        comment = f"* Generated {now.isoformat()}Z"
        netlist = "\n".join(self.HEADER + [comment] + body_lines + self.FOOTER)
        return netlist

    def save(self, path: str, netlist_text: str) -> None:
        with open(path, "w") as f:
            f.write(netlist_text)
        print(f"Netlist written to {path}") 